### ISSUE TITLE
IPOPT for python 3.7 

### ISSUE THREAD

**Issue by TamerSobhy** [romcon/OPTALG#2]
Hey @awig and @swaroopguggilam

I think ipopt option is not working for Python 3.7. I am trying to solve OPF with IPOPT and it returns an error:

 module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'optalg.opt_solver._ipopt.cipopt'

But, I can solve the problem with option "inlp " solver. 

Cheers,
Tamer

**Comment by swaroopguggilam** [comment]
Hey @TamerSobhy 
When you install GAT from source, it asks the user to install IPOPT and MUMPS, you should select "yes" to that option.
Can you try this and let us know if it works?

**Comment by TamerSobhy** [comment]
I tried and I got this error:
TypeError: '>=' not supported between instances of 'NoneType' and 'str'

**Comment by swaroopguggilam** [comment]
I spent some time today trying to get this working but had no luck.
Here are my findings:
1) In the link https://github.com/matthias-k/cyipopt#example-installation-on-ubuntu-1804-with-custom-compiled-ipopt following note has been mentioned - 
Only conda Python has been tested to work at the moment, and not the official python.org distribution. There is likely a binary compatibility issue between the C compiler used to build IPOPT and that used for compiling Python extensions in the official Python distribution (see https://github.com/matthias-k/cyipopt/issues/52).
So looks like there is known issue for direct installation.
So we might have to download the ipopt and set up the OPTALG installation using IPOPT in a different way.
2) Documentation for the IPOPT - https://projects.coin-or.org/Ipopt/browser/stable/3.9/Ipopt/doc/documentation.pdf?format=raw
3) Most places I have searched for, people have pointed to following link https://coin-or.github.io/Ipopt/INSTALL.html for installation
- I couldn't get it working in the short amount I spend. But we might need to make/build the IPOPT from source and then install to get it working.

**Comment by TamerSobhy** [comment]
I think the problem is with Mumps. When I am running nosetests, test_mumps returns an error and test_ipopt is ok.
Also, I tried installing the packages on Anaconda python 3.7.4 and I got the same error:

    self.id.irn = self.cast_array(irn)
  File "optalg\lin_solver\_mumps\_dmumps.pyx", line 152, in optalg.lin_solver._mumps._dmumps.DMUMPS_STRUC_C.irn.__set__
    def __set__(self, unsigned long value): self.ob.irn = <MUMPS_INT*> value
OverflowError: Python int too large to convert to C unsigned long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\EPRI_work\Code\OPTALG\tests\test_opt_solvers.py", line 644, in test_solvers_on_LPs
    except opt.opt_solver.OptSolverError_NotAvailable:
AttributeError: module 'optalg.opt_solver' has no attribute 'OptSolverError_NotAvailable'

**Comment by swaroopguggilam** [comment]
Here is my nosetests output
`(test_gat) C:\Users\psgu004\Documents\my_romcom\OPTALG>nosetests -s -v
test_mumps (tests.test_lin_solvers.TestOptSolvers) ... SKIP: no mumps
test_superlu (tests.test_lin_solvers.TestOptSolvers) ... ok
test_umfpack (tests.test_lin_solvers.TestOptSolvers) ... SKIP: no umfpack
test_augl_barrier (tests.test_opt_solvers.TestOptSolvers) ... ok
test_augl_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_cbc (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_cbc_cmd (tests.test_opt_solvers.TestOptSolvers) ... ok
test_cbc_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... ok
test_cbc_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_cbc_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_clp (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_clp_cmd (tests.test_opt_solvers.TestOptSolvers) ... ERROR
test_clp_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... ERROR
test_clp_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_clp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_cplex_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex command-line solver
test_cplex_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_cplex_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_inlp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_ipopt_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_ipopt_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_iqp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_iqp_random (tests.test_opt_solvers.TestOptSolvers) ... ok
test_nr_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_LPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_QPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_lin_to_lp_file (tests.test_problems.TestProblems) ... ok
test_mixintlin_to_lp_file (tests.test_problems.TestProblems) ... ok

======================================================================
ERROR: test_clp_cmd (tests.test_opt_solvers.TestOptSolvers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\psgu004\Documents\my_romcom\OPTALG\tests\test_opt_solvers.py", line 450, in test_clp_cmd
    solver.solve(problem)
  File "C:\Users\psgu004\Documents\my_romcom\OPTALG\optalg\opt_solver\clp_cmd.py", line 123, in solve
    raise OptSolverError_ClpCMD(self)
optalg.opt_solver.opt_solver_error.OptSolverError_ClpCMD: clp command-line solver failed

======================================================================
ERROR: test_clp_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\psgu004\Documents\my_romcom\OPTALG\tests\test_opt_solvers.py", line 357, in test_clp_cmd_lp_duals
    solver.solve(problem)
  File "C:\Users\psgu004\Documents\my_romcom\OPTALG\optalg\opt_solver\clp_cmd.py", line 123, in solve
    raise OptSolverError_ClpCMD(self)
optalg.opt_solver.opt_solver_error.OptSolverError_ClpCMD: clp command-line solver failed

----------------------------------------------------------------------
Ran 29 tests in 6.880s

FAILED (SKIP=12, errors=2)`
So  even after successfull install ->
1) It is not detecting Mumps
2) It is not detecting IpOPT
3) Error in CLPCMD solver

**Comment by TamerSobhy** [comment]
The output shows that you don't have ipopt: **test_ipopt (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt**
**

**Comment by swaroopguggilam** [comment]
Yes, As I mentioned in my comment at the end, even after successfull install, not sure why its not detecting mumps and ipopt.

**Comment by TamerSobhy** [comment]
Did you set OPTALG_IPOPT=true  before installing OPTALG ?

**Comment by swaroopguggilam** [comment]
Yes I did.

**Comment by TamerSobhy** [comment]
Here is the output of nosetests on my machine:  **Without setting OPTALG_IPOPT=true**

test_mumps (tests.test_lin_solvers.TestOptSolvers) ... SKIP: no mumps
test_superlu (tests.test_lin_solvers.TestOptSolvers) ... ok
test_umfpack (tests.test_lin_solvers.TestOptSolvers) ... SKIP: no umfpack
test_augl_barrier (tests.test_opt_solvers.TestOptSolvers) ... ok
test_augl_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_cbc (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_cbc_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc command-line solver
test_cbc_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_clp (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_clp_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp command-line solver
test_clp_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_cplex_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex command-line solver
test_cplex_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_cplex_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_inlp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_ipopt_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_ipopt_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_iqp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_iqp_random (tests.test_opt_solvers.TestOptSolvers) ... ok
test_nr_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_LPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_QPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_lin_to_lp_file (tests.test_problems.TestProblems) ... ok
test_mixintlin_to_lp_file (tests.test_problems.TestProblems) ... ok

----------------------------------------------------------------------
Ran 29 tests in 8.389s

OK (SKIP=18)


And here is the output with setting "OPTALG_IPOPT=true" 
test_mumps (tests.test_lin_solvers.TestOptSolvers) ... ERROR
test_superlu (tests.test_lin_solvers.TestOptSolvers) ... ok
test_umfpack (tests.test_lin_solvers.TestOptSolvers) ... SKIP: no umfpack
test_augl_barrier (tests.test_opt_solvers.TestOptSolvers) ... ok
test_augl_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_cbc (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_cbc_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc command-line solver
test_cbc_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_clp (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_clp_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp command-line solver
test_clp_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_cplex_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex command-line solver
test_cplex_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_cplex_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_inlp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_iqp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_iqp_random (tests.test_opt_solvers.TestOptSolvers) ... ERROR
test_nr_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_LPs (tests.test_opt_solvers.TestOptSolvers) ... ERROR
test_solvers_on_QPs (tests.test_opt_solvers.TestOptSolvers) ... ERROR
test_lin_to_lp_file (tests.test_problems.TestProblems) ... ok
test_mixintlin_to_lp_file (tests.test_problems.TestProblems) ... ok

======================================================================
ERROR: test_mumps (tests.test_lin_solvers.TestOptSolvers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\EPRI_work\Code\OPTALG\tests\test_lin_solvers.py", line 63, in test_mumps
    mumps.analyze(A)
  File "D:\EPRI_work\Code\OPTALG\optalg\lin_solver\mumps.py", line 57, in analyze
    self.mumps.set_centralized_assembled_rows_cols(A.row+1,A.col+1)
  File "D:\EPRI_work\Code\OPTALG\optalg\lin_solver\_mumps\__init__.py", line 120, in set_centralized_assembled_rows_cols
    self.id.irn = self.cast_array(irn)
  File "optalg\lin_solver\_mumps\_dmumps.pyx", line 152, in optalg.lin_solver._mumps._dmumps.DMUMPS_STRUC_C.irn.__set__
    def __set__(self, unsigned long value): self.ob.irn = <MUMPS_INT*> value
OverflowError: Python int too large to convert to C unsigned long

======================================================================
ERROR: test_iqp_random (tests.test_opt_solvers.TestOptSolvers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\EPRI_work\Code\OPTALG\tests\test_opt_solvers.py", line 604, in test_iqp_random
    solver.solve(prob)
  File "D:\EPRI_work\Code\OPTALG\optalg\opt_solver\iqp.py", line 238, in solve
    self.linsolver.analyze(Jbar)
  File "D:\EPRI_work\Code\OPTALG\optalg\lin_solver\mumps.py", line 57, in analyze
    self.mumps.set_centralized_assembled_rows_cols(A.row+1,A.col+1)
  File "D:\EPRI_work\Code\OPTALG\optalg\lin_solver\_mumps\__init__.py", line 120, in set_centralized_assembled_rows_cols
    self.id.irn = self.cast_array(irn)
  File "optalg\lin_solver\_mumps\_dmumps.pyx", line 152, in optalg.lin_solver._mumps._dmumps.DMUMPS_STRUC_C.irn.__set__
    def __set__(self, unsigned long value): self.ob.irn = <MUMPS_INT*> value
OverflowError: Python int too large to convert to C unsigned long

======================================================================
ERROR: test_solvers_on_LPs (tests.test_opt_solvers.TestOptSolvers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\EPRI_work\Code\OPTALG\tests\test_opt_solvers.py", line 643, in test_solvers_on_LPs
    solver.solve(problem)
  File "D:\EPRI_work\Code\OPTALG\optalg\opt_solver\inlp.py", line 233, in solve
    self.linsolver.analyze(Jbar)
  File "D:\EPRI_work\Code\OPTALG\optalg\lin_solver\mumps.py", line 57, in analyze
    self.mumps.set_centralized_assembled_rows_cols(A.row+1,A.col+1)
  File "D:\EPRI_work\Code\OPTALG\optalg\lin_solver\_mumps\__init__.py", line 120, in set_centralized_assembled_rows_cols
    self.id.irn = self.cast_array(irn)
  File "optalg\lin_solver\_mumps\_dmumps.pyx", line 152, in optalg.lin_solver._mumps._dmumps.DMUMPS_STRUC_C.irn.__set__
    def __set__(self, unsigned long value): self.ob.irn = <MUMPS_INT*> value
OverflowError: Python int too large to convert to C unsigned long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\EPRI_work\Code\OPTALG\tests\test_opt_solvers.py", line 644, in test_solvers_on_LPs
    except opt.opt_solver.OptSolverError_NotAvailable:
AttributeError: module 'optalg.opt_solver' has no attribute 'OptSolverError_NotAvailable'

======================================================================
ERROR: test_solvers_on_QPs (tests.test_opt_solvers.TestOptSolvers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\EPRI_work\Code\OPTALG\tests\test_opt_solvers.py", line 693, in test_solvers_on_QPs
    IQP.solve(prob)
  File "D:\EPRI_work\Code\OPTALG\optalg\opt_solver\iqp.py", line 238, in solve
    self.linsolver.analyze(Jbar)
  File "D:\EPRI_work\Code\OPTALG\optalg\lin_solver\mumps.py", line 57, in analyze
    self.mumps.set_centralized_assembled_rows_cols(A.row+1,A.col+1)
  File "D:\EPRI_work\Code\OPTALG\optalg\lin_solver\_mumps\__init__.py", line 120, in set_centralized_assembled_rows_cols
    self.id.irn = self.cast_array(irn)
  File "optalg\lin_solver\_mumps\_dmumps.pyx", line 152, in optalg.lin_solver._mumps._dmumps.DMUMPS_STRUC_C.irn.__set__
    def __set__(self, unsigned long value): self.ob.irn = <MUMPS_INT*> value
OverflowError: Python int too large to convert to C unsigned long

----------------------------------------------------------------------
Ran 29 tests in 1.030s

FAILED (SKIP=14, errors=4)

**Comment by TamerSobhy** [comment]
In my case, the test of mump gives an error

**Comment by swaroopguggilam** [comment]
Hmm ok. I am not sure why its giving "clp command-line solver failed", don't know how it's detecting that.

**Comment by awig** [comment]
FYI. I need to `python setup.py build_ext --inplace` before running the tests. But, on my mac ipopt works just fine for Python3.7. Here are the results of the tests:

```
(venv37) pawi002@pawi002-MBP OPTALG % nosetests -v -s
test_mumps (tests.test_lin_solvers.TestOptSolvers) ... ok
test_superlu (tests.test_lin_solvers.TestOptSolvers) ... ok
test_umfpack (tests.test_lin_solvers.TestOptSolvers) ... SKIP: no umfpack
test_augl_barrier (tests.test_opt_solvers.TestOptSolvers) ... ok
test_augl_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_cbc (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_cbc_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc command-line solver
test_cbc_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_clp (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_clp_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp command-line solver
test_clp_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_cplex_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex command-line solver
test_cplex_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_cplex_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_inlp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_iqp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_iqp_random (tests.test_opt_solvers.TestOptSolvers) ... ok
test_nr_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_LPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_QPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_lin_to_lp_file (tests.test_problems.TestProblems) ... ok
test_mixintlin_to_lp_file (tests.test_problems.TestProblems) ... ok

----------------------------------------------------------------------
Ran 29 tests in 4.943s

OK (SKIP=14)
(venv37) pawi002@pawi002-MBP OPTALG %
```


So, if we can get Swaroop to the same point as Tamer then we can be more certain that it is a MUMPS on Windows issue.

**Comment by awig** [comment]
So I ran it on my old windows laptop and got the same `OverflowError: Python int too large to convert to C unsigned long` as Tamer.  I'll have to look into that, hopefully it is some settings that we can provide to the compiler that provides a workaround or something we can change in the pyx file on our end.

**Comment by swaroopguggilam** [comment]
oh ok. That's nice, at least you both have consistent errors. Not sure, why its not detecting/working in mine.

**Comment by awig** [comment]
First error occurs in `_dmumps.pyx` on line 153:
``        def __set__(self, unsigned long value): self.ob.irn = <MUMPS_INT*> value``

MUMPTS_INT is defined on line 20:
``    ctypedef int MUMPS_INT``

**Comment by awig** [comment]
Need to figure out why this particular cast on Windows fails for Python3/Cython. Hopefully changing it on windows won't brake it elsewhere.

**Comment by swaroopguggilam** [comment]
Got rid of that clp command error issue. But the OPTALG still is unable to find ipopt or mumps.
Steps I followed:
1) Pip uninstall optalg
2)clean.bat (modified the code, it deletes the .c files as well)
3) python setup.py build_ext --inplace
4) nosetests -s -v
```
(test_optalg) C:\Users\psgu004\Documents\my_romcom\OPTALG>nosetests -s -v
test_mumps (tests.test_lin_solvers.TestOptSolvers) ... SKIP: no mumps
test_superlu (tests.test_lin_solvers.TestOptSolvers) ... ok
test_umfpack (tests.test_lin_solvers.TestOptSolvers) ... SKIP: no umfpack
test_augl_barrier (tests.test_opt_solvers.TestOptSolvers) ... ok
test_augl_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_cbc (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_cbc_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc command-line solver
test_cbc_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_clp (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_clp_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp command-line solver
test_clp_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_cplex_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex command-line solver
test_cplex_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_cplex_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_inlp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_ipopt_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_ipopt_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_iqp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_iqp_random (tests.test_opt_solvers.TestOptSolvers) ... ok
test_nr_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_LPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_QPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_lin_to_lp_file (tests.test_problems.TestProblems) ... ok
test_mixintlin_to_lp_file (tests.test_problems.TestProblems) ... ok

----------------------------------------------------------------------
Ran 29 tests in 6.566s

OK (SKIP=18)
```

**Comment by swaroopguggilam** [comment]
As we have two separate issues on this thread,
1) Tamer's - Variable type error (Fix found, PR sent, Adam needs to test)
2) Swaroop - IPOPT is not detected (opening this as a separate issue)

**Comment by entriken** [comment]
Tracing down to OPTALG/lib/ipopt/include/coin/ThirdParty/mumps_c_types.h
Line 55
#define MUMPS_INT int

Previously, @awig noted that MUMPS_INT is defined on line 20:
ctypedef int MUMPS_INT

These two definitions will be consistent, as long as they are converted by the same compilers.

The error says a Python int is being cast to a C unsigned long, per @TamerSobhy 
File "optalg\lin_solver_mumps_dmumps.pyx", line 152, in optalg.lin_solver._mumps._dmumps.DMUMPS_STRUC_C.irn.set
def set(self, unsigned long value): self.ob.irn = <MUMPS_INT*> value

Note that the actual file location is: 'OPTALG/optalg/lin_solver/_mumps/_dmumps.pyx'.

Since the value is being passed by pointer '<MUMPS_INT*>', perhaps instead of MUMPS_INT*, the pointer needs to be cast as 'uintptr'?

**Comment by entriken** [comment]
Not knowing enough about Python, perhaps, also, the unsigned long should be a uintptr?  Perhaps other pointers need to be revised?

**Comment by awig** [comment]
Closed working on all platforms assuming ipopt and mumps are found appropriately.
